#!/bin/bash

# exit if not enabled in config
if [ "$(cat /opt/motd/config.json | jq '.motd.show.plexpy' --raw-output)" == "false" ]; then exit 0; fi

source /opt/motd/colors.txt

data=$(python3 /opt/motd/cloudbox-motd.py plexpy get_stream_counts)

if [[ $data == ERROR* ]]
then
    plex_transcodes=0
    plex_direct_plays=0
    plex_direct_streams=0
else
    IFS='.' read -r -a array <<< "$data"
    plex_transcodes=${array[0]}
    plex_direct_plays=${array[1]}
    plex_direct_streams=${array[2]}
fi

echo -e " ${TITLE_COLOR}Plex Streams........:${NC} Transcodes: ${TEXT_COLOR}${plex_transcodes}${NC} | Direct Plays: ${TEXT_COLOR}${plex_direct_plays}${NC} | Direct Streams: ${TEXT_COLOR}${plex_direct_streams}${NC}"
echo -e " ${TITLE_COLOR}Plex Tx.............:${NC} Up: ${TEXT_COLOR}$(python3 /opt/motd/cloudbox-motd.py plexpy get_stream_bandwidth)${NC}"

