#!/bin/bash

source /opt/motd/colors.txt

data=$(python3 /opt/motd/cloudbox-motd.py rtorrent get_torrent_counts)
if [[ $data == ERROR* ]]
then
    rtorrent_torrents=0
    rtorrent_downloading=0
    rtorrent_seeding=0
else
    IFS='.' read -r -a array <<< "$data"
    rtorrent_torrents=${array[0]}
    rtorrent_downloading=${array[1]}
    rtorrent_seeding=${array[2]}
fi

echo -e " ${TITLE_COLOR}Torrents............:${NC} Total: ${TEXT_COLOR}${rtorrent_torrents}${NC} | Downloading: ${TEXT_COLOR}${rtorrent_downloading}${NC} | Uploading: ${TEXT_COLOR}${rtorrent_seeding}${NC}"
echo -e " ${TITLE_COLOR}Torrents Rx/Tx......:${NC} Down: ${TEXT_COLOR}$(python3 /opt/motd/cloudbox-motd.py rtorrent get_download_rate)${NC} | Up: ${TEXT_COLOR}$(python3 /opt/motd/cloudbox-motd.py rtorrent get_upload_rate)${NC}"
echo -e " ${TITLE_COLOR}Torrents Bandwidth..:${NC} Downloaded: ${TEXT_COLOR}$(python3 /opt/motd/cloudbox-motd.py rtorrent get_download_total)${NC} | Uploaded: ${TEXT_COLOR}$(python3 /opt/motd/cloudbox-motd.py rtorrent get_upload_total)${NC}"