#!/bin/bash

source /opt/motd/colors.txt

data=$(python3 /opt/motd/cloudbox-motd.py nzbget get_nzb_counts)
if [[ $data == ERROR* ]]
then
    nzbget_nzbs=0
    nzbget_downloading=0
    nzbget_paused=0
	nzbget_unpacking=0
	nzbget_repairing=0
	nzbget_verifying=0
else
    IFS='.' read -r -a array <<< "$data"
	nzbget_nzbs=${array[0]}
    nzbget_downloading=${array[1]}
    nzbget_paused=${array[2]}
	nzbget_unpacking=${array[3]}
	nzbget_repairing=${array[4]}
	nzbget_verifying=${array[5]}
fi

echo -e " ${YEL}Nzbs................:${NC} Total: ${PUR}${nzbget_nzbs}${NC} | Downloading: ${PUR}${nzbget_downloading}${NC} | Paused: ${PUR}${nzbget_paused}${NC} | Unpack: ${PUR}${nzbget_unpacking}${NC} | Repair: ${PUR}${nzbget_repairing}${NC} | Verify: ${PUR}${nzbget_verifying}${NC}"
echo -e " ${YEL}Nzbs Rx.............:${NC} Down: ${PUR}$(python3 /opt/motd/cloudbox-motd.py nzbget get_download_rate)${NC}"
echo -e " ${YEL}Nzbs Bandwidth......:${NC} Downloaded: ${PUR}$(python3 /opt/motd/cloudbox-motd.py nzbget get_download_total)${NC}"
